### ISSUE TITLE
Extra arguments to set call not dispatched with internal redirects

### ISSUE THREAD

**Issue by oliwel** [whiterabbitsecurity/connector#50]
It seems that the "data" hash that can be passed with the `set` method does not survive an internal redirect on top of connector.

While the `direct` call in this example receives the publication data, the indirect call does not.

```yaml
crl:
    direct@: connector:publishing.connector.crl2f5
    reflected@: publishing.targets.crl2f5.node1

targets:
  crl2f5@: connector:publishing.connector.crl2f5

connector:
  crl2f5:
     class: ....
```
